[package]
name = "hashbrown-time"
version = "0.1.0"
authors = ["BudiNverse <me@inve.rs>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
justbus-utils = { path = "../justbus-utils" }
ahash = "0.7.6"