name: Test Rust project
on: [push]
jobs:
  build-swisstable:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - uses: BudiNverse/setup-rust-action@v1
      with:
        linux-mold-version: "1.3.0"
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo build --features swisstable,logging,hw-lock-elision,tls,msft-mimalloc,fxhash

  build-dashmap:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - uses: BudiNverse/setup-rust-action@v1
      with:
        linux-mold-version: "1.3.0"
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo build --features dashmap,logging,tls,msft-mimalloc,fxhash

  build-nightly:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - uses: BudiNverse/setup-rust-action@v1
      with:
        linux-mold-version: "1.3.0"
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo build --features swisstable,nightly,logging,tls,msft-mimalloc,fxhash