name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Swisstable
        run: cargo check --features swisstable --verbose
      - name: Check Dashmap
        run: cargo check --features dashmap --verbose
      - name: Check logging and tls
        run: cargo check --features swisstable,logging,tls --verbose