name: Test Rust project
on: [push]
jobs:
  build-swisstable:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - uses: rui314/setup-mold@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Build executable
      run: cargo build --features swisstable,logging,hw-lock-elision,tls,msft-mimalloc,fxhash
    - name: Check executable
      run: readelf -p .comment ./target/debug/justbus-rs

  build-dashmap:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - uses: rui314/setup-mold@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Build executable
      run: cargo build --features dashmap,logging,tls,msft-mimalloc,fxhash
    - name: Check executable
      run: readelf -p .comment ./target/debug/justbus-rs


  build-nightly:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - uses: rui314/setup-mold@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Build executable
      run: cargo build --features swisstable,nightly,logging,tls,msft-mimalloc,fxhash
    - name: Check executable
      run: readelf -p .comment ./target/debug/justbus-rs
